repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: functional-tests
        name: Functional tests
        entry: pixi run pytest tests/functional/ -x -q --reuse-db
        language: system
        types: [python]
        pass_filenames: false
