# Generated by Django 5.2 on 2026-02-01 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_garage', '0003_add_collector_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_history', to='my_garage.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
