# Generated by Django 5.2.9 on 2026-02-13 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("my_garage", "0006_collectiontype_dynamiccollectionitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericupgrade",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="genericupgrade",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="genericupgrade",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upgrades",
                to="my_garage.dynamiccollectionitem",
            ),
        ),
    ]
