# Generated by Django 5.2.9 on 2026-03-29 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_garage", "0009_phase1_collection_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerecord",
            name="vehicle",
        ),
        migrations.RemoveField(
            model_name="timepiece",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="upgrade",
            name="vehicle",
        ),
        migrations.RemoveField(
            model_name="valuationhistory",
            name="vehicle",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="owner",
        ),
        migrations.DeleteModel(
            name="ConditionReport",
        ),
        migrations.DeleteModel(
            name="ServiceRecord",
        ),
        migrations.DeleteModel(
            name="Timepiece",
        ),
        migrations.DeleteModel(
            name="Upgrade",
        ),
        migrations.DeleteModel(
            name="ValuationHistory",
        ),
        migrations.DeleteModel(
            name="Vehicle",
        ),
    ]
