# Generated by Django 5.2.11 on 2026-06-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_garage", "0011_portfolio_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamiccollectionitem",
            name="net_financial_position",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cached NFP: market value minus all-in cost basis",
                max_digits=12,
                null=True,
            ),
        ),
    ]
