# Generated by Django 5.2.11 on 2026-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_garage", "0012_dynamiccollectionitem_net_financial_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamiccollectionitem",
            name="total_cost_basis",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cached cost basis: purchase price + services + completed upgrades",
                max_digits=12,
                null=True,
            ),
        ),
    ]
