# Generated by Django 5.2.11 on 2026-06-10 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_garage", "0017_estateaccesstoken_valuationsnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="estateaccesstoken",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estate_access_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
