# Generated by Django 5.2.11 on 2026-08-15 14:09

from django.db import migrations, models

# FontAwesome 6 requires a style-family prefix; a bare "fa-box" renders nothing.
# Older rows were created before this was understood (and from the old model
# default), so backfill them to the solid family.
_FA6_STYLE_FAMILIES = ("fa-solid", "fa-regular", "fa-brands", "fas", "far", "fab")


def add_fa6_style_prefix(apps, schema_editor):
    CollectionType = apps.get_model("my_garage", "CollectionType")
    for ctype in CollectionType.objects.all():
        icon = (ctype.icon or "").strip()
        if not icon:
            ctype.icon = "fa-solid fa-box"
        elif not any(part in _FA6_STYLE_FAMILIES for part in icon.split()):
            ctype.icon = f"fa-solid {icon}"
        else:
            continue
        ctype.save(update_fields=["icon"])


def remove_fa6_style_prefix(apps, schema_editor):
    """No-op: the prefixed form is valid FA6 and safe to leave in place."""


class Migration(migrations.Migration):
    dependencies = [
        ("my_garage", "0018_alter_estateaccesstoken_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectiontype",
            name="icon",
            field=models.CharField(
                default="fa-solid fa-box",
                help_text="FontAwesome icon class (FA6 needs a style prefix, e.g. 'fa-solid fa-car')",  # noqa: E501
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="collectiontype",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.RunPython(add_fa6_style_prefix, remove_fa6_style_prefix),
    ]
